### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by jbeguna04** [Jhonnyc/ToolBox#1]
Hello @Jhonnyc , Greetings!
Im a graphics designer and I would to ask for your permission to propose an icon/logo for your project. Hoping for your response and Good luck to your project :)

Best Regards,
-jbeguna04

**Comment by Jhonnyc** [comment]
Hi @jbeguna04 ,
This project is basically a library project and not an actual app, if you still want to create a logo for it you can :) (would appreciate if you can share the final result with me).
